### ISSUE TITLE
[3.0.1] the doc is missing

### ISSUE THREAD

**Issue by picca** [Codra-Ingenierie-Informatique/guidata#59]
I try to package this version but all the doc is missing on pypi.

Cheers

**Comment by PierreRaybaut** [comment]
Currently, using setuptools + pyproject.toml, it's very hard to differentiate the contents of the source package and the wheel package. Apparently, everybody thinks it's normal to distribute the same contents with the two formats. That's why I was forced to remove the documentation folder from the source package... but clearly, that's not a good idea! I'll get back to it to find another solution.

**Comment by picca** [comment]
I am wondering if you can not use the MANIFEST.in file for this purpose...

**Comment by PierreRaybaut** [comment]
Exactly :)

That's funny, we had the same idea at the same time :).
Actually, using a MANIFEST.in was part of my previous attempts but setuptools has a very strange and complicated behaviour regarding this. I found a workaround which is to use a MANIFEST.in with just ``graft doc`` in it. It works but... I just hope that the behavior does not change in the next release of setuptools!
